### ISSUE TITLE
Example landscapeText not working properly

### ISSUE THREAD

**Issue by imabot2** [Seeed-Studio/TFT_Touch_Shield_V2#14]
The example landscapeText just display the two first texts. The others are not displayed. 

By the way, I wonder if LANDSCAPE_UPSIDE_DOWN is working properly. 

Hardware :
- seeeduino v4.2
- 2.8 inch TFT Touch Shield v2.0
- Arduino 1.8.10

**Comment by hansonCc** [comment]
Thanks for your feedback, I updated this library. and you can get the newest library by using git clone https://github.com/Seeed-Studio/TFT_Touch_Shield_V2.git

**Comment by imabot2** [comment]
It now works perfectly. Thank you.
