### ISSUE TITLE
TFTDriver = readID() called two too many times

### ISSUE THREAD

**Issue by PerryCodes** [Seeed-Studio/TFT_Touch_Shield_V2#5]
This is what currently exists in TFTv2.cpp

for(i=0;i<3;i++)
{
     TFTDriver = readID();
}

Is this intentional?  If so, what is the reason?  I get the correct value the first and third time (0x09341), but for some reason it's read as 0x08141 the second time through this loop.  Why would that be happening?

**Comment by Pillar1989** [comment]
Refer to https://github.com/Seeed-Studio/TFT_Touch_Shield_V2/commit/8341ed7e50ca8b8cc92e1315e43176ce11b2d4ed
