### ISSUE TITLE
tftbmp2 no longer compiles on Arduino Uno - 150% of RAM

### ISSUE THREAD

**Issue by PerryCodes** [Seeed-Studio/TFT_Touch_Shield_V2#6]
This compiles for Mega, but not UNO (which I would guess to be the most popular Arduino).

**Comment by Pillar1989** [comment]
Refer to https://github.com/Seeed-Studio/TFT_Touch_Shield_V2/commit/8341ed7e50ca8b8cc92e1315e43176ce11b2d4ed
