### ISSUE TITLE
Is there a way to flip the screen round?

### ISSUE THREAD

**Issue by trunkyredstone** [Seeed-Studio/TFT_Touch_Shield_V2#9]
Is there anyway to flip the screen around, i just want to write text horizontally not vertically

**Comment by TimoK93** [comment]
Same here!

**Comment by Pillar1989** [comment]
Refer to https://github.com/Seeed-Studio/TFT_Touch_Shield_V2/commit/8341ed7e50ca8b8cc92e1315e43176ce11b2d4ed
